### PR TITLE
Improvements and fixes

### LINKED ISSUE #291: Crash on radar-schemas 0.3.4
The management portal crashes when it uses catalog server with radar-schemas 0.3.4. I'm assuming this is because it does not understand the newly created `CONNECTOR` source type, and that doesn't have a vendor, model and version.

Ideally, the management portal should not crash when it encounters a wrong source type, but warn and ignore instead.

### PR DESCRIPTION
**Pull request by nivemaham**
- Adds `privacyPolicyUrl` property to MetaQR code response
- Ignores errors during source-type loading from catalog server with warning message.
- Adds configuration to override default admin password. 
Fixes #291 #297 #289

### CODE REVIEW

File: src/main/java/org/radarcns/management/web/rest/SubjectResource.java [hunk 1]
```diff
@@ -441,18 +427,31 @@
                         sourceDto.getSourceTypeCatalogVersion()).getId();
 
         }
+
+        // check the subject id
+        Subject sub = subjectService.findOneByLogin(login);
+
+        // find the actively assigned project for this subject
+        Optional<Project> activeProject = sub.getActiveProject();
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/management/web/rest/SubjectResource.java]: use `orElseThrow`?

File: src/main/java/org/radarcns/management/domain/Subject.java [hunk 2]
```diff
@@ -155,6 +158,26 @@ public void setAttributes(Map<String, String> attributes) {
...
+     * and the project that is related to that role is the active role.</p>
+     *
+     * @return {@link Project} currently active project of subject.
+     */
+    public Optional<Project> getActiveProject() {
+        Optional<Role> activeProjectRole = this.getUser().getRoles().stream()
+                .filter(r -> r.getAuthority().getName().equals(PARTICIPANT))
+                .findFirst();
+
+        if (activeProjectRole.isPresent()) {
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/management/domain/Subject.java]: instead of if/else, you can do
```java
return activeProjectRole.map(Role::getProject);
```

Comment (blootsvoets) [reply src/main/java/org/radarcns/management/domain/Subject.java]: Or even do that one line up:
```
...
.findFirst()
.map(Role::getProject);
```

File: src/main/java/org/radarcns/management/service/OAuthClientService.java [hunk 3]
```diff
@@ -201,15 +205,55 @@ public ClientPairInfoDTO createRefreshToken(Subject subject, String clientId)
...
+     */
+    private URL getPrivacyPolicyUrl(Subject subject) {
+
+        Optional<Project> project = subject.getActiveProject();
+
+        // load default url from config
+        String policyUrl = managementPortalProperties.getCommon().getPrivacyPolicyUrl();
+
+        // override from project specific url if available.
+        if (project.isPresent()) {
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/management/service/OAuthClientService.java]: the lines above can be shortened to:
```java
String policyUrl = subject.getActiveProject()
    .map(p -> p.getAttributes().get(PRIVACY_POLICY_URL))
    .filter(u -> u != null && !u.isEmpty())
    .orElse(managementPortalProperties.getCommon().getPrivacyPolicyUrl());
```

File: src/main/java/org/radarcns/management/service/OAuthClientService.java [hunk 4]
```diff
@@ -201,15 +205,55 @@ public ClientPairInfoDTO createRefreshToken(Subject subject, String clientId)
...
+            if (projectPrivacyPolicyUrl != null && !projectPrivacyPolicyUrl.isEmpty()) {
+                policyUrl = projectPrivacyPolicyUrl;
+            }
+        }
+
+        try {
+            return new URL(policyUrl);
+        } catch (MalformedURLException e) {
+            Map<String, String> params = new HashMap<>();
+            params.put("Url" , policyUrl);
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/management/service/OAuthClientService.java]: lowercase `url`?

File: src/main/java/org/radarcns/management/service/mapper/decorator/SubjectMapperDecorator.java [hunk 5]
```diff
@@ -39,12 +38,10 @@ public SubjectDTO subjectToSubjectDTO(Subject subject) {
...
         SubjectDTO dto = delegate.subjectToSubjectDTO(subject);
         dto.setStatus(getSubjectStatus(subject));
-        Optional<Role> role = subject.getUser().getRoles().stream()
-                .filter(r -> r.getAuthority().getName().equals(AuthoritiesConstants.PARTICIPANT))
-                .findFirst();
-
-        role.ifPresent(role1 ->
-                dto.setProject(projectMapper.projectToProjectDTO(role1.getProject())));
+        Optional<Project> activeProject = subject.getActiveProject();
+        if (activeProject.isPresent()) {
```
Comment (blootsvoets) [inline src/main/java/org/radarcns/management/service/mapper/decorator/SubjectMapperDecorator.java]: why not `ifPresent(project -> dto.setProject(projectMapper.projectToProjectDTO(project)))`?

Comment (nivemaham) [reply src/main/java/org/radarcns/management/service/mapper/decorator/SubjectMapperDecorator.java]: Pushed the changes. Thanks for the suggestions.
